version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hono_postgres
    environment:
      POSTGRES_DB: hono_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "11432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: